spring:
  data:
    mongodb:
      host: comfortfeeling.zi0os.mongodb.net
      port: 27017
      database: comfort_feeling
      username: admin
      password: sundo0528soft

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create