spring:
  data:
    mongodb:
      database: comfort_feeling
      uri: mongodb+srv://admin:sundo0528soft@comfortfeeling.zi0os.mongodb.net/comfort_feeling

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: upgrade